### ISSUE TITLE
Improve z-move input

### ISSUE THREAD

**Issue by MagiaSN** [Zarel/honko-damagecalc#100]
It seems power of z-moves can only be assigned manually now. I think it would be better if we just type the original move, then check a checkbox or something, and got the corresponding z-move used for calc.
Is anyone working on this? I can have a try if not :)

**Comment by AustinXII** [comment]
@MagiaSN I'm working on this just haven't had any time on a computer recently, feel free to check my repo and either take over from where I am or make a PR with the remaining missing code

**Comment by MagiaSN** [comment]
@AustinXII I have written the other part except move data #101 . When you complete updating move data, they can be merged together.

**Comment by AustinXII** [comment]
@MagiaSN Alright seeing how you went ahead and did the other parts I'll really try to get in some time to finish this weekend, thanks again +1

**Comment by AustinXII** [comment]
#101
