### ISSUE TITLE
All vs One and One vs All Sort Incorrect

### ISSUE THREAD

**Issue by daviddonnelly** [Zarel/honko-damagecalc#126]
https://pokemonshowdown.com/damagecalc/calc_bc.html?mode=all-vs-one
https://pokemonshowdown.com/damagecalc/calc_bc.html?mode=one-vs-all
Damage (%) and KO Chance column sort
When clicking the column headers to sort by damage, it looks like it's incorrectly sorting alphabetically rather than a number value sort.
e.g.
0
101.5
11
122
13.2
whereas it should be
0
11
13.2
101.5
122
I believe the last time I used this functionality was 2016-07-XX. It was working at that time.
Please take a look.
Thanks!

**Comment by MagiaSN** [comment]
#128
