### ISSUE TITLE
Improve accessibility for screen readers

### ISSUE THREAD

**Issue by Neurrone** [Zarel/honko-damagecalc#149]
Similar to [the corresponding issue for the Showdown client](https://github.com/Zarel/Pokemon-Showdown-Client/issues/954). Unfortunately, this will be much harder than the client, as that only needed usability improvements.

* [ ] The generation radio buttons are not recognized as such, they just read as plain text. There is no indication which is selected, or that they are a logical group. Might be because <input> elements need to always be inside a `<form>`, or associated with one using an attribute, so this looks like invalid html5. Similarly for the notation and mode radio buttons on the top, the move selection, single/doubles, terrain selection, weather selection, and spike layers radios.
* [x] What's this used for? `<span id="damageValues">(211, 214, 216, 218, 220, 224, 226, 227, 231, 234, 235, 238, 242, 243, 246, 250)</span>`
* [ ] When the page loads, below pokemon1, I hear "Abomasnow (ORAS NU Mixed Attacker)" being announced as a link. Only by pressing enter do I hear my focus moving into an edit field. I can edit the text, but it doesn't read suggestions when pressing up/down, or announce the presence of suggestions. When I press escape to stop editing, I hear 2 edit boxes now, one of them is probably not meant for editing, so should be `aria-hidden`.
* [x] The crit and z checkboxes are not recognized as such, but read as plain text, with no indication of being checked/unchecked. Similarly, the gravity, stealth rocks, reflect, light screen, protect, leech seed, Foresight, Helping Hand, Friend Guard and Aurora Veil checkboxes. 
* [ ] For controls that can affect either side of the field (e.g, hazards), should be labeled so it differentiates between yours and opponent's side.

**Comment by AustinXII** [comment]
This is a cool idea, I'll respond in more depth later when I have more time 👍

**Comment by MagiaSN** [comment]
> What's this used for? <span id="damageValues">(211, 214, 216, 218, 220, 224, 226, 227, 231, 234, 235, 238, 242, 243, 246, 250)</span>

This lists all possible damage values, maybe we could add `speak: none` to it as it is seldom needed?

> When the page loads, below pokemon1, I hear "Abomasnow (ORAS NU Mixed Attacker)" being announced as a link.

>  When I press escape to stop editing, I hear 2 edit boxes now, one of them is probably not meant for editing, so should be aria-hidden.

This seems a select2 issue, it renders the select2 widget with an `<a>` element, which is read as a link. As for the two `<input>` elements, one is what we used to initialize the select2 widget and store the value of the selected set; the other is generated by select2 to make the widget focusable.

For the first `<input>`, we could simply add `aria-hidden` to it; however for the second `<input>` and the `<a>`, as they are generated by select2, maybe we need to hack if we want to add attributes to them :(

> The crit and z checkboxes are not recognized as such, but read as plain text, with no indication of being checked/unchecked. Similarly, the gravity, stealth rocks, reflect, light screen, protect, leech seed, Foresight, Helping Hand, Friend Guard and Aurora Veil checkboxes.

These elements has css property `display: none` for visual effects, I think this prevents the screen reader from reading them.


I will do some further investigations, and create some PRs later.

**Comment by Neurrone** [comment]
@MagiaSN Removing this from the CSS fixes the issues with all checkboxes and radio buttons, but obviously changes the visual layout.

```css
.btn-input {
    display: none;
}
```

I can try finding out how to fix it without changing it visually.

Now that I know what the damage values are, it shouldnt be `aria-hidden`, as it is a visible part of the UI that contains information.

**Comment by Neurrone** [comment]
What is `calc_bc.html` for? Seems like a copy of index.html

**Comment by MagiaSN** [comment]
@Neurrone This page is for one-vs-all and all-vs-one calculation

**Comment by Neurrone** [comment]
@MagiaSN thanks. Will port the improvements over from `index.html` to the other page once I'm done.

**Comment by AustinXII** [comment]
``calc_bc`` should probably be renamed for clariety any suggestions @MagiaSN ?

**Comment by MagiaSN** [comment]
@AustinXII Would `honkalculate.html` be fine?

**Comment by MagiaSN** [comment]
Perhaps `ap_calc.js` `calc_ab.js` should be renamed too

**Comment by AustinXII** [comment]
@MagiaSN Yeah I like the first name and yeah all those should be renamed for clarity, suggestions?

**Comment by MagiaSN** [comment]
@AustinXII I think we could rename `ap_calc.js` to `shared_controls.js`, `calc_ab.js` to `index_controls.js`, and `calc_bc.js` to `honkalculate_controls.js`

**Comment by AustinXII** [comment]
I like it, opinions @Zarel maybe also @Honko if he wants to weigh in

**Comment by Zarel** [comment]
sure

**Comment by Neurrone** [comment]
Only thing left now is the third item.
