### ISSUE TITLE
All vs One for VGC 17 broken

### ISSUE THREAD

**Issue by jarrjam** [Zarel/honko-damagecalc#155]
When clicking the 'Honkalculate' button for All vs One VGC 17, no damage calculations are produced. I did a bit of investigating and it seems to be a problem with Vanilluxe using Sheer Cold which gives an undefined 'move.type' value. After I used Chrome's inbuilt debugger to create an IF statement that sets 'move.type' to Ice when Sheer Cold is used, the problem went away. I don't know why the problem only happens for VGC 17, however.

**Comment by AustinXII** [comment]
I'll do the fix later

**Comment by AustinXII** [comment]
(If you're curious, Sheer Cold had a ZP value but was never defined before Sun and Moon so it was missing all its basic info (move type, effects, etc))

**Comment by MagiaSN** [comment]
@AustinXII It seems you were busy, so I made a quick fix #156
