### ISSUE TITLE
problem looking up the Tapus

### ISSUE THREAD

**Issue by bjoernboombastic** [Zarel/honko-damagecalc#169]
Hey 
Lately there appears a new little handling inconvenience when typing in the Tapus in the damage calculator. 
The calculator seems to not perceive the space between 'Tapu' and Bulu/Lele/Koko/Fini ofcourse you can type Tapu in the search mask and look up the one you need manually but I remember a (maybe?) similar bug during ORAS when it appears to say 'Blank Set' for every Pokémon with a hyphen in its name which you could fix quite fast therefore I hope this is only a little issue too :)

Good job Man!

**Comment by AustinXII** [comment]
Hey @honko you're the only one who changed the search function recently, any ideas?
