### ISSUE TITLE
Suggestion: Add Costum set for base forms

### ISSUE THREAD

**Issue by bjoernboombastic** [Zarel/honko-damagecalc#170]
Hey 
I want to suggest an addition too, 
thinking it would be a nice feature if you could choose 'Costum Set' with Ash-Greninja in regular Greninja form or when you using a mega but you arent mega evolved yet. 
I don't know a single thing about scripting therefore I want to apologize if this is a insanely complicated to implement idea. 

Again, keeping up the great work!

**Comment by AustinXII** [comment]
You can always import the set then change the polemons forme with the forme change button. Doing this will make the new forme have its base formes sets
