### ISSUE TITLE
Ring Target has no effect

### ISSUE THREAD

**Issue by SadisticMystic** [Zarel/honko-damagecalc#173]
This one's easy; just set up a scenario where one of the attacker's moves is blocked by an immunity. Then change the defender's item to Ring Target. It should override the immunity and allow it to show some actual damage, but doesn't.

**Comment by AustinXII** [comment]
You should be more specific, the defenders immunities that are from its typing are negated

**Comment by SadisticMystic** [comment]
It's not just type-based immunities: Pikachu Thunderbolt vs. Ring Target Lightning Rod Seaking: 0-0 (0 - 0%) -- aim for the horn next time

**Comment by AustinXII** [comment]
But yes will do

**Comment by AustinXII** [comment]
Ring target doesn’t change that, The ps dex states “The holder's type immunities granted solely by its typing are negated” @Marty-D please confirm

**Comment by SadisticMystic** [comment]
Just tested in game: tricked Ring Target onto a wild Haunter, used EQ, no damage and still got the Levitate popup.

**Comment by Ntonio36** [comment]
Soo should we close this issue then ?

**Comment by AustinXII** [comment]
.. no there still is a issue with it not negating typing immunities

**Comment by Ntonio36** [comment]
@AustinXII you still up for it ? I feel i can handle this one pretty easily

**Comment by Ntonio36** [comment]
Done. Now awaiting merging.

**Comment by AustinXII** [comment]
Yeah it’s an easy one just haven’t had time to be on a computer, but yes feel free to tackle anything that isn’t done
