### ISSUE TITLE
RBY/GSC mix up stat order when determining HP IV

### ISSUE THREAD

**Issue by SadisticMystic** [Zarel/honko-damagecalc#182]
Nowadays, the canonical ordering of stats is HP-AT-DF-SA-SD-SP, but it was originally ordered as HP-AT-DF-SP-SC, and that's the order that's reflected in the G1 and G2 data structure. If you go into one of those modes and set the Special IV to 14, HP is also supposed to drop to 14 because the low bit there is also the low bit for HP, but the calculator actually sets HP to 13 there, as though it thinks Special controls the 2 bit of HP. That bit is really supposed to be intermeshed with Speed, and setting a 14 there should drop HP to 13 in the absence of anything else, but instead the calc goes to 14 HP--a straight relabeling of the stat order.

**Comment by Ntonio36** [comment]
So, as far as I understood, the Speed DVs actually weigh 2 bits while the Special DVs only weigh one ?

**Comment by AustinXII** [comment]
No I think it’s just an issue with the code not being tuned correctly for older gens since it’s mixing up the stat order. It’s presumably using gen3+ stat order in gens 1&2

**Comment by Ntonio36** [comment]
@SadisticMystic I made a PR that might fix the problem(s), could you test and notify me whether this has solved the issue globally ?

**Comment by Ntonio36** [comment]
@AustinXII you can close this issue now :).

**Comment by AustinXII** [comment]
Fixed in #194
