### ISSUE TITLE
Offline iOS app

### ISSUE THREAD

**Issue by HebrewLantern** [Zarel/honko-damagecalc#191]
Any chance of making an offline capable iOS app?

**Comment by AustinXII** [comment]
I was actually going to look into this a year-ish ago but stopped when my laptop broke, perhaps one day. This would probably be done in React so it’s A droid and IOS compatible

**Comment by Davey-Hughes** [comment]
On this vein, do you think it would be possible to add/convert this to a NodeJS compatible library? If this is a possibility, I'm happy to help with development, though my JS and Pokemon mechanics knowledge aren't the best.

It seems that it would be possible to separate out the pure JS files from the web/JQuery notation/functions, but considering how integrated the DOM interaction is with the core of the calculator code, it doesn't look like a fun task.

**Comment by AustinXII** [comment]
@Davey-Hughes that’s probably for zarel to decide.

**Comment by Ntonio36** [comment]
Thinking about it, I wonder how could this be made... Could you mention how might this library used please, @Davey-Hughes?

**Comment by tunanut** [comment]
What about mobile web, Since you're considering React

**Comment by Hidden50** [comment]
Does it need to be an iOS app? An html5 service worker sounds easier to do, and it would provide offline access for all operating systems.

Here's an example, though you'll also need to make a manifest if you want to make it a web app (that the user can be prompted to install to their home screen, it'll run within their browser in offline mode when they tap the icon).

https://gist.github.com/Hidden50/3c62a415745f931385a0036ce1ad70c8

**Comment by tunanut** [comment]
> Does it need to be an iOS app? An html5 service worker sounds easier to do, and it would provide offline access for all operating systems.

Agreed.  Damage calc actually doesn't need that many native-only features or accessibilities.  and it'll be much easier to publish.

**Comment by scheibo** [comment]
I'm closing this in favor of #327.

> On this vein, do you think it would be possible to add/convert this to a NodeJS compatible library? If this is a possibility, I'm happy to help with development, though my JS and Pokemon mechanics knowledge aren't the best.
>
> It seems that it would be possible to separate out the pure JS files from the web/JQuery notation/functions, but considering how integrated the DOM interaction is with the core of the calculator code, it doesn't look like a fun task.

Yes, I in fact did this, @Davey-Hughes. It wasn't a super fun task :). See the `calc/` subfolder, it will soon be published on NPM as `@pokemon-showdown/calc`.
