### ISSUE TITLE
When loading a custom set on the right side, Abomasnow form remains, messing up calc

### ISSUE THREAD

**Issue by penpexgit** [Zarel/honko-damagecalc#213]
I followed the following steps:
Load this set:
```
Necrozma-Dusk-Mane @ Solganium Z  
Ability: Prism Armor  
EVs: 252 Atk / 4 Def / 252 Spe  
Adamant Nature  
- Sunsteel Strike  
- Photon Geyser  
- Prismatic Laser  
- Brick Break  
```

then load this set:
```
Gengar  
Ability: Cursed Body  
IVs: 0 Atk  
- Will-O-Wisp 
```

Both imported with success.
Then on the left side, I select 'Only show imported sets', then select my Necrozma-Dusk-Mane set.
Then on the right I select my Gengar manually from the list (since _there is no 'Only show imported sets ' option on the right_).
Then the calc shows this:
`252+ Atk Necrozma-Dusk-Mane Photon Geyser vs. 0 HP / 0 Def `**Abomasnow**`: 584-690 (181.9 - 214.9%) -- guaranteed OHKO`
Yes, Abomasnow, and in the right field, everything has Gengar's stuff, _except_ the 'Forme' field, that still has Abomasnow, so the error night come from here. After that if you try to change the Pokémon on the right to like Abra or some other, and then reselect my Gengar set, a lot of weird stuff happens, sometimes it will work, sometimes the previous Pokémon will still show up...
So I'm not sure what's happening exactly but it is not right. And yeah, **would be nice to have the 'Only show imported sets' option on the right side too.**

**Comment by Ntonio36** [comment]
Planned. It'll take some time, but planned anyways.

**Comment by penpexgit** [comment]
The bug I described above is still there, so this should be reopened.
Doing the exact same thing as described above (except now I can use "Only show imported sets" on the right too, thanks for that!) I get the same wrong caclc result:
`252+ Atk Necrozma-Dusk-Mane Photon Geyser vs. 0 HP / 0 Def **Abomasnow**: 584-690 (181.9 - 214.9%) -- guaranteed OHKO`
