### ISSUE TITLE
Missing moves: Disarming Voice and Water Gun

### ISSUE THREAD

**Issue by wartab** [Zarel/honko-damagecalc#223]
Don't know if it's intended, but you can't have Water Gun nor Disarming Voice in the calculator. 
We use this calculator a lot to calculate damage ranges for speedruns and since the Gen 7 speedruns use Popplio, it's tedious to always replace values of other moves.

I'd make a pull request, but my repo contains other changes on the master branch that are related to speedruns, so I cannot just make a pull request of that. Nevertheless this commit should suffice: https://github.com/wartab/honko-damagecalc/commit/a7f8142aa8dcd73f9c0c509fd92dcad7ebb00e3c

**Comment by Ntonio36** [comment]
Could you tell me what are the missing other moves (if any), so I simply can put them all at once?

**Comment by AustinXII** [comment]
Fixed in #222
