### ISSUE TITLE
Bubble Beam is Special, not Physical

### ISSUE THREAD

**Issue by wartab** [Zarel/honko-damagecalc#224]
https://github.com/wartab/honko-damagecalc/commit/e3762445f86da42cf65fbebbac012eb346a312f1

**Comment by Ntonio36** [comment]
Instead of stacking your commits on master branch, just create a separate branch and merge a PR from it..

**Comment by wartab** [comment]
As I said in my other Pull Request, this fork has another purpose and is not compatible with this repo anymore. If really needed, I'll do it this weekend.

**Comment by Ntonio36** [comment]
Never mind then, I'll handle it.

**Comment by AustinXII** [comment]
I don’t believe that holds you back, I’ve done multiple PRs when my fork was serverly outdated.

**Comment by wartab** [comment]
It is not outdated, I modified its feature set to help routing speedruns for Pokémon games. As I said, I'll only have time to do that properly this weekend. If you are wondering what I mean, you can see the result here: http://wartab.be/damage-calc/

**Comment by AustinXII** [comment]
Fixed in #222
