### ISSUE TITLE
Automatic move highlighting picks lowest damaging move

### ISSUE THREAD

**Issue by aturfah** [Zarel/honko-damagecalc#232]
Picking Passimian when Abomasnow is already loaded defaults to Passimian's Earthquake
Picking Ferroseed when Passimian is already loaded defaults to Passimian's Rock Slide
Picking Magmortar when Ferroseed is already loaded defaults to Magmortar's Thunderbolt
If (No Move) is available it chooses that.

Sometimes it picks the status moves (Recover for Mareanie vs Ferroseed) sometimes it doesn't (Ferroseed vs Passimian)

**Comment by Ntonio36** [comment]
I believe that was fixed a while ago. Check out #229.

**Comment by aturfah** [comment]
Gotcha, thank you much
