### ISSUE TITLE
Picking Regigigas (BH Poison Heal) still gives Slow Start as the ability, same goes for other BH sets

### ISSUE THREAD

**Issue by ElMustacho** [Zarel/honko-damagecalc#276]

**Comment by AustinXII** [comment]
In need of a new computer but when i buy one I’ll look into the calc again. I’ve been too leanient on code standards I suppose. I probably should have just waited until I could have done everything myself to avoid to calcs current state :/

**Comment by AustinXII** [comment]
fixed
