### ISSUE TITLE
Weakness Policy is missing

### ISSUE THREAD

**Issue by tunanut** [Zarel/honko-damagecalc#284]
Seeing it checks 'weakness policy' for `getFlingPower`  https://github.com/Zarel/honko-damagecalc/blob/master/js/data/item_data.js#L436
but it's not in the item list

**Comment by tunanut** [comment]
Hmm I guess this item doesn't have anything to do with damage calc.. Now I understand

**Comment by AustinXII** [comment]
@tunanut nope it’s only used for the bad fling option
