### ISSUE TITLE
Alolan Raticate base HP is incorrect when selecting Alolan form from the sub menu

### ISSUE THREAD

**Issue by wartab** [Zarel/honko-damagecalc#298]
I couldn't find how to fix this myself, so I apolgize for not submitting a PR.
Seems like the HP value is not transferred if it changes in an alternate form?

![Bug](https://i.gyazo.com/258a7fb9ec993bf21c4c96ae6f09ffab.png)
Base is 75 for Alolan form, not 55.

**Comment by AustinXII** [comment]
HP wasn't apart of STATS so it would never get updated
