### ISSUE TITLE
No Crits

### ISSUE THREAD

**Issue by GreyBM** [Zarel/honko-damagecalc#305]
Noticed this while playing with Z-Tailwind, but the calc isn't displaying critical hit damage when prompted.

Also, I'm unsure if the calc is updated with analysis sets automatically or not but there's quite a few sets from upwards of 3 months ago that have been uploaded on the smogdex but aren't on the calc, e.g. Victreebel's Strength Sap set, Bouffalant's SubSD set, SubToxic Kangaskhan and Gastrodon's PU spread. I've been making do using custom sets, but it'd be great if these could be uploaded as default sets. Thanks for all the hard work!

**Comment by AustinXII** [comment]
Was fixed a few days ago, waiting on an update

**Comment by AustinXII** [comment]
@Zarel I haven’t seen you or TI on in a few days, probably just bad timing on my end. BTW Marty doesn’t have client access which could be handy if you’re willing to give it to him.

**Comment by Zarel** [comment]
I updated
