### ISSUE TITLE
Mold Breaker is not being calculated

### ISSUE THREAD

**Issue by Arbbib** [Zarel/honko-damagecalc#308]
Mold breaker is not affecting damage. For example, mold breaker haxorus at +2 attack does the same to unaware clefable as an unboosted haxorus

**Comment by AustinXII** [comment]
I was waiting to see if asgdf was going to make a pull request, for now I’m not going to touch mold breaker until pre finishes his refactoring / tests

**Comment by scheibo** [comment]
> until pre finishes his refactoring / tests

I haven't started coding yet

**Comment by AustinXII** [comment]
@scheibo still going to wait unless I randomly get inspired to tackle it again.

**Comment by scheibo** [comment]
>  I’m curious how you did moldbreaker and if it evaluates differently than mains

I didn't actually (intend to) change anything in my refactoring writh respect to functionality, so presumably my code still have the same bugs wrt moldbreaker as the main repo.

**Comment by AustinXII** [comment]
@scheibo I know but at least after I can just make a moldbreaker test so it doesn’t break again and is a lot more obvious if it’ll work. Also I’m kinda banking on typescript finding the error 😜

**Comment by AustinXII** [comment]
@scheibo well at least I can add some tests for it to prevent it breaking for no reason in the future
