### ISSUE TITLE
Simple beam (move) not in the move list for any pokemon yet

### ISSUE THREAD

**Issue by inspiredorigami** [Zarel/honko-damagecalc#319]
Simple beam doesn't seem to be anywhere in the moves list.  I know that Beheeyem, Linoone, Xatu, Audino, etc. should all be able to use simple beam, but it does not seem to be possible to select it as a move.

**Comment by Zarel** [comment]
Is this necessary? Can't you just manually select Simple from the ability list?

**Comment by AustinXII** [comment]
^ that’s the reason it isn’t added, it’s a lot of hand holding and the only way we could implement it currently would make people say “why is simple my ability just because a Pokémon has simple beam????”
