### ISSUE TITLE
Lycanroc-Dusk Stat Errors

### ISSUE THREAD

**Issue by Checkmate8397** [Zarel/honko-damagecalc#321]
Lycanroc-Dusk has 115 base attack and 112 base speed in the calc not its actual stat of 117 and 110 respectively.

**Comment by AustinXII** [comment]
``"Lycanroc-Dusk": {
		"t1": "Rock",
		"bs": {
			"hp": 75,
			"at": 117,
			"df": 65,
			"sa": 55,
			"sd": 65,
			"sp": 110
		},
		"w": 25.0,
		"isAlternateForme": true
	},
``

**Comment by AustinXII** [comment]
?

**Comment by Checkmate8397** [comment]
![image](https://user-images.githubusercontent.com/52177326/60356189-43b5af00-99c8-11e9-94e2-bc89c28a3799.png)
Assuming the image uploads this is how lycanroc-dusk's stats are, which isn't what they actually are.

**Comment by AustinXII** [comment]
> ![image](https://user-images.githubusercontent.com/52177326/60356189-43b5af00-99c8-11e9-94e2-bc89c28a3799.png)
> Assuming the image uploads this is how lycanroc-dusk's stats are, which isn't what they actually are. It essentially has Lycanroc-midday's stats.

It says ``forme Lycanroc``...

**Comment by Checkmate8397** [comment]
![image](https://user-images.githubusercontent.com/52177326/60373344-bc802f80-99f7-11e9-8ef6-b9e3137535c7.png)

**Comment by Marty-D** [comment]
I can't believe no one noticed it was misspelled until I looked at it for two seconds.

**Comment by AustinXII** [comment]
> I can't believe no one noticed it was misspelled until I looked at it for two seconds.

I didn’t have time to actually look into it, I just looked at the lycanroc-dusk property . Anyways thanks

**Comment by AustinXII** [comment]
My 2 seconds was worse than yours tho :(
