### ISSUE TITLE
CSS broken at https://pokemonshowdown.com/damagecalc/

### ISSUE THREAD

**Issue by Novocastrian** [Zarel/honko-damagecalc#325]
The CSS on the damage calc page refuses to load in Firefox or Edge on Windows 10, nor Firefox on Android.
<details><summary>Screenshot from Windows 10:</summary>
<img src="https://user-images.githubusercontent.com/4601813/61165976-d62e8480-a56a-11e9-8013-9481ec2d3f7a.png">
</details>

Here's the console log whenever loading the page:<details>
  <summary>Click to expand!</summary>
  The script from “https://pokemonshowdown.com/damagecalc/js/lodash.min.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen6.js?97195ee6” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen3.js?536677a2” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/jquery-1.9.1.min.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/pokedex.js?87e6ce3d” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/select2/select2.min.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen5.js?e9f980ec” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen7.js?f1810552” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/stat_data.js?5a66b065” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen4.js?0c34ff8e” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/move_data.js?20346a6c” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/nature_data.js?0b9893dd” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen2.js?b100018c” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/type_data.js?b9e89839” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen1.js?31a0a173” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/ability_data.js?f8043e11” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/data/item_data.js?e12edd58” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/damage_gen4.js?f6c18cbe” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/index_controls.js?28a210e0” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/damage_gen2.js?9c23e706” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/damage.js?10b386c3” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/shared_controls.js?5f42ddb0” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/damage_gen3.js?d60cb282” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/moveset_import.js?e7204e96” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/damage_gen1.js?339cf0fe” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/ko_chance.js?4a5c6196” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
The script from “https://pokemonshowdown.com/damagecalc/js/jquery-1.9.1.min.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/jquery-1.9.1.min.js”. damagecalc:1358:1
The script from “https://pokemonshowdown.com/damagecalc/js/lodash.min.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/lodash.min.js”. damagecalc:1359:1
The script from “https://pokemonshowdown.com/damagecalc/select2/select2.min.js” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/select2/select2.min.js”. damagecalc:1360:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/pokedex.js?87e6ce3d” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/pokedex.js?87e6ce3d”. damagecalc:1361:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen7.js?f1810552” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen7.js?f1810552”. damagecalc:1362:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen6.js?97195ee6” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen6.js?97195ee6”. damagecalc:1363:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen5.js?e9f980ec” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen5.js?e9f980ec”. damagecalc:1364:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen4.js?0c34ff8e” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen4.js?0c34ff8e”. damagecalc:1365:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen3.js?536677a2” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen3.js?536677a2”. damagecalc:1366:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen2.js?b100018c” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen2.js?b100018c”. damagecalc:1367:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen1.js?31a0a173” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/setdex_gen1.js?31a0a173”. damagecalc:1368:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/stat_data.js?5a66b065” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/stat_data.js?5a66b065”. damagecalc:1369:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/type_data.js?b9e89839” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/type_data.js?b9e89839”. damagecalc:1370:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/nature_data.js?0b9893dd” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/nature_data.js?0b9893dd”. damagecalc:1371:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/ability_data.js?f8043e11” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/ability_data.js?f8043e11”. damagecalc:1372:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/item_data.js?e12edd58” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/item_data.js?e12edd58”. damagecalc:1373:1
The script from “https://pokemonshowdown.com/damagecalc/js/data/move_data.js?20346a6c” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/data/move_data.js?20346a6c”. damagecalc:1374:1
The script from “https://pokemonshowdown.com/damagecalc/js/shared_controls.js?5f42ddb0” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/shared_controls.js?5f42ddb0”. damagecalc:1375:1
The script from “https://pokemonshowdown.com/damagecalc/js/index_controls.js?28a210e0” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/index_controls.js?28a210e0”. damagecalc:1376:1
The script from “https://pokemonshowdown.com/damagecalc/js/damage.js?10b386c3” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/damage.js?10b386c3”. damagecalc:1377:1
The script from “https://pokemonshowdown.com/damagecalc/js/damage_gen4.js?f6c18cbe” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/damage_gen4.js?f6c18cbe”. damagecalc:1378:1
The script from “https://pokemonshowdown.com/damagecalc/js/damage_gen3.js?d60cb282” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/damage_gen3.js?d60cb282”. damagecalc:1379:1
The script from “https://pokemonshowdown.com/damagecalc/js/damage_gen2.js?9c23e706” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/damage_gen2.js?9c23e706”. damagecalc:1380:1
The script from “https://pokemonshowdown.com/damagecalc/js/damage_gen1.js?339cf0fe” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/damage_gen1.js?339cf0fe”. damagecalc:1381:1
The script from “https://pokemonshowdown.com/damagecalc/js/ko_chance.js?4a5c6196” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/ko_chance.js?4a5c6196”. damagecalc:1382:1
The script from “https://pokemonshowdown.com/damagecalc/js/moveset_import.js?e7204e96” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type. damagecalc
Loading failed for the <script> with source “https://pokemonshowdown.com/damagecalc/js/moveset_import.js?e7204e96”. damagecalc:1383:1

</details>
I've cleared the cache on both my phone and PC, rebooted, ensured Firefox and Edge are upto date, and still replicate this issue. In its current state, it doesn't appear to import team lists at all.
Issue persists via Wi-Fi and Mobile data (4G), so is definitely not a network issue on my end.

**Comment by Zarel** [comment]
We apparently botched an update.

Should be fixed now.

**Comment by Novocastrian** [comment]
Yep! Fixed. Thanks for the quick resolution - much appreciated :)
