### ISSUE TITLE
Add analytics around page views and which modes are being used

### ISSUE THREAD

**Issue by scheibo** [Zarel/honko-damagecalc#329]
- Set up a new property for the damage calc in Google Analytics
- add something like following snippet:

```html
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-XXXXXX-X', 'pokemonshowdown.com/damagecalc');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
<script>
	window.onerror = function(err, uri, line) {
		var msg = uri + ':' + line + ': ' + err;
		if ('ga' in window) {
			ga('send', 'event', 'Client error', msg);
		} else {
			alert('ERROR: ' + msg);
		}
		return false;
	};
</script>
```

Though we also want to track:
  -  `generation`
  - `mode` (one vs one, one vs all, all vs one)
  - `format` (standard, vgc, random, bss, etc)

**Comment by Zarel** [comment]
Actually, if you guys want to make your own Analytics account or something? Or does it have to be me?

**Comment by scheibo** [comment]
I mean, its hosted on your domain, I feel it'd make for sense for you to set it up. It'd be nice if you [granted us access to it](https://www.monsterinsights.com/docs/how-to-grant-user-access-in-google-analytics/) though.

**Comment by Zarel** [comment]
I remember giving others Analytics access used to be a mess, but it might have been fixed by now.

**Comment by scheibo** [comment]
Reopening to track Austin and I getting access to the dashboard and tracking gen/mode properly.

**Comment by AustinXII** [comment]
I think I’m going to make a new google account for this so I’ll commit when I’ve done that

**Comment by scheibo** [comment]
> Can you setup listening for client errors?

_Originally posted by @Zarel in https://github.com/Zarel/honko-damagecalc/pull/341#issuecomment-520622483_
