### ISSUE TITLE
Importing Sets does not work

### ISSUE THREAD

**Issue by AustinXII** [Zarel/honko-damagecalc#34]
Currently when you take the sets directly from teambuilder the moves will not appear. Edit: Marty has confirmed this is from the extra space Teambuilder adds to support reddit

**Comment by Marty-D** [comment]
Those screenshots aren't actually a before and after; they're two different Excadrill sets. You should be looking for the "VTH.Excadrill" set after importing, not "FWG.Excadrill". Seems to work fine for me.
