### ISSUE TITLE
Beat Up is not on the calc?

### ISSUE THREAD

**Issue by dtsong** [Zarel/honko-damagecalc#55]
Hey there, just noticed that Beat Up isn't among the listed moves for a Pokemon to use. I wanted to do Beat Up calcs from a Whimsicott on a Focus Sash Gengar, but it seems that I can't do that because Beat Up isn't a listed move.

**Comment by AustinXII** [comment]
Considering beat up's damage is based on the attack stats of your idle Pokemon I don't think this will be added

**Comment by Guernouille** [comment]
This would require you to type the other Pokémon. It's probably manageable to display 5 fields when the move is selected. Not sure it is worth it though. Might be useful to add it to the calc for niches like Gen 2 / Gen 3 Houndoom I guess.

**Comment by Zarel** [comment]
Closing because the amount of data needed to be entered is kind of ridiculous. People can customize the stats and bp used in calculations, anyway, so if they actually want to do the calculation, it's still possible.
