### ISSUE TITLE
Function isGrounded is missing

### ISSUE THREAD

**Issue by MagiaSN** [Zarel/honko-damagecalc#90]
Function isGrounded is called in getTerrainEffects (defined in calc_ab.js), but I can't find its definition.
When I check Electric Terrain and Misty Terrain, a script error occurred and their effects are not applied. Grassy Terrain and Psychic Terrain work fine.
Please have a look at this.

**Comment by AustinXII** [comment]
This bug dates back to when @augmt first added terrains, seems like he forgot about it.

**Comment by MagiaSN** [comment]
I have opened a pull request #93
